/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;


import controle.FornecedorCL;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import negocio.CNPJBO;
import negocio.EnderecoBO;
import negocio.FornecedorBO;

/**
 *
 * @author Marcos
 */
public class FornecedorUI extends javax.swing.JInternalFrame {

    /**
     * Creates new form FornecedorUI
     */
    public FornecedorUI() {
        initComponents();
    }
    public FornecedorBO read(){
      int codigoFornecedor = Integer.parseInt(txtCodigoFornecedor.getText());
        String nomeFantasia =txtNomeFantasia.getText();
        String razao = txtRazaoSocial.getText();
        String email = txtEmailFornecedor.getText();
        String telefone = txtTelefoneFornecedor.getText();
        String cnpj = txtCNPJ.getText();
        CNPJBO cnpjFornecedor = new CNPJBO(cnpj);
        String contato = txtContato.getText();
        
        String estado = txtEstadoFornecedor.getText();
        String cidade = txtCidadeFornecedor.getText();
        String bairro = txtBairroFornecedor.getText();
        String logradouro = txtLogradouroFornecedor.getText();
        String complemento = txtComplementoFornecedor.getText();
        int numero = Integer.parseInt(txtNumeroFornecedor.getText());
        String cep = txtCepFornecedor.getText();
        
        EnderecoBO endereco = new EnderecoBO(estado, cidade, bairro, logradouro, complemento, numero, cep);
        
        FornecedorBO f = new FornecedorBO(codigoFornecedor, nomeFantasia, razao, email, telefone, cnpjFornecedor,endereco, contato );
    return f;
    }
    
    public void limpaTelaFornecedor(){
        txtCodigoFornecedor.setText("");
     txtNomeFantasia.setText("");
            txtRazaoSocial.setText("");
            txtEmailFornecedor.setText("");
            txtTelefoneFornecedor.setText("");
            txtCNPJ.setText("");
            txtContato.setText("");
            txtEstadoFornecedor.setText("");
            txtCidadeFornecedor.setText("");
            txtBairroFornecedor.setText("");
            txtLogradouroFornecedor.setText("");
            txtComplementoFornecedor.setText("");
            txtNumeroFornecedor.setText("");
            txtCepFornecedor.setText("");
            
    }
    public void CriatabelaVazia(){
     DefaultTableModel modelo = new DefaultTableModel();
      modelo.addColumn("Código");
      modelo.addColumn("Nome");
      modelo.addColumn("telefone");
      modelo.addColumn("email");
      modelo.addColumn("Razao social");
       tblFornecedor.setModel(modelo);
    }
    public void retrieveFornecedor(){
     DefaultTableModel modelo = new DefaultTableModel();
      modelo.addColumn("Código");
      modelo.addColumn("Nome");
      modelo.addColumn("telefone");
      modelo.addColumn("email");
      modelo.addColumn("Razao social");

         for(FornecedorBO c: FornecedorCL.showFornecedores()){
        modelo.addRow(new Object[] {
        c.getCodigo(), c.getNomeFantasia(), c.getTelefone(), c.geteMail(), c.getRazaoSocial()
        });
        }
            tblFornecedor.setModel(modelo);
    }
    public void writeFornecedor(FornecedorBO f){
            txtNomeFantasia.setText(f.getNomeFantasia());
            txtCodigoFornecedor.setText(String.valueOf(f.getCodigo()));
            txtRazaoSocial.setText(f.getRazaoSocial());
            txtEmailFornecedor.setText(f.geteMail());
            txtTelefoneFornecedor.setText(f.getTelefone());
            txtCNPJ.setText(String.valueOf(f.getCnpj().getNumero()));
            txtContato.setText(f.getContato());
            txtEstadoFornecedor.setText(f.getEndereco().getEstado());
            txtCidadeFornecedor.setText(f.getEndereco().getCidade());
            txtBairroFornecedor.setText(f.getEndereco().getBairro());
            txtLogradouroFornecedor.setText(f.getEndereco().getLogradouro());
            txtComplementoFornecedor.setText(f.getEndereco().getComplemento());
            txtNumeroFornecedor.setText(String.valueOf(f.getEndereco().getNumero()));
            txtCepFornecedor.setText(f.getEndereco().getCep());
            
    
    }
    
    
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCodigoFornecedor = new javax.swing.JLabel();
        txtCodigoFornecedor = new javax.swing.JTextField();
        lblNomeFantasia = new javax.swing.JLabel();
        lblRazaoSocial = new javax.swing.JLabel();
        txtNomeFantasia = new javax.swing.JTextField();
        txtRazaoSocial = new javax.swing.JTextField();
        lblEmailFornecedor = new javax.swing.JLabel();
        txtEmailFornecedor = new javax.swing.JTextField();
        lblTelefoneFornecedor = new javax.swing.JLabel();
        txtTelefoneFornecedor = new javax.swing.JTextField();
        lblCNPJ = new javax.swing.JLabel();
        txtCNPJ = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtContato = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtCidadeFornecedor = new javax.swing.JTextField();
        txtEstadoFornecedor = new javax.swing.JTextField();
        txtBairroFornecedor = new javax.swing.JTextField();
        txtLogradouroFornecedor = new javax.swing.JTextField();
        txtComplementoFornecedor = new javax.swing.JTextField();
        txtNumeroFornecedor = new javax.swing.JTextField();
        txtCepFornecedor = new javax.swing.JTextField();
        btnLimpaCampos = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFornecedor = new javax.swing.JTable();
        btnLimpa = new javax.swing.JButton();

        setClosable(true);
        setResizable(true);
        setTitle("Módulo de fornecedores");
        setPreferredSize(new java.awt.Dimension(820, 653));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));

        lblCodigoFornecedor.setText("Código:");

        txtCodigoFornecedor.setBackground(new java.awt.Color(204, 204, 204));
        txtCodigoFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoFornecedorActionPerformed(evt);
            }
        });

        lblNomeFantasia.setText("Nome Fantasia:");

        lblRazaoSocial.setText("Razão social:");

        txtNomeFantasia.setBackground(new java.awt.Color(204, 204, 204));

        txtRazaoSocial.setBackground(new java.awt.Color(204, 204, 204));

        lblEmailFornecedor.setText("Email:");

        txtEmailFornecedor.setBackground(new java.awt.Color(204, 204, 204));
        txtEmailFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailFornecedorActionPerformed(evt);
            }
        });

        lblTelefoneFornecedor.setText("Telefone:");

        txtTelefoneFornecedor.setBackground(new java.awt.Color(204, 204, 204));
        txtTelefoneFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefoneFornecedorActionPerformed(evt);
            }
        });

        lblCNPJ.setText("CNPJ:");

        txtCNPJ.setBackground(new java.awt.Color(204, 204, 204));
        txtCNPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCNPJActionPerformed(evt);
            }
        });

        jLabel1.setText("Estado:");

        jLabel2.setText("Cidade:");

        jLabel3.setText("Bairro:");

        jLabel4.setText("Logradouro:");

        jLabel5.setText("Complemento:");

        jLabel6.setText("Número:");

        jLabel7.setText("Contato:");

        txtContato.setBackground(new java.awt.Color(204, 204, 204));
        txtContato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContatoActionPerformed(evt);
            }
        });

        jLabel8.setText("cep:");

        txtCidadeFornecedor.setBackground(new java.awt.Color(204, 204, 204));

        txtEstadoFornecedor.setBackground(new java.awt.Color(204, 204, 204));

        txtBairroFornecedor.setBackground(new java.awt.Color(204, 204, 204));

        txtLogradouroFornecedor.setBackground(new java.awt.Color(204, 204, 204));

        txtComplementoFornecedor.setBackground(new java.awt.Color(204, 204, 204));

        txtNumeroFornecedor.setBackground(new java.awt.Color(204, 204, 204));

        txtCepFornecedor.setBackground(new java.awt.Color(204, 204, 204));

        btnLimpaCampos.setText("Limpa campos");
        btnLimpaCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpaCamposActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(lblEmailFornecedor)
                            .addGap(59, 59, 59))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblCodigoFornecedor)
                                .addComponent(lblNomeFantasia)
                                .addComponent(lblRazaoSocial)
                                .addComponent(lblTelefoneFornecedor))
                            .addGap(5, 5, 5)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCNPJ)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNomeFantasia)
                                    .addComponent(txtCodigoFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtEmailFornecedor)
                            .addComponent(txtTelefoneFornecedor)
                            .addComponent(txtCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)))
                                    .addGap(8, 8, 8)))
                            .addComponent(jLabel5)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtContato, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCidadeFornecedor)
                    .addComponent(txtBairroFornecedor)
                    .addComponent(txtLogradouroFornecedor)
                    .addComponent(txtComplementoFornecedor)
                    .addComponent(txtNumeroFornecedor)
                    .addComponent(txtCepFornecedor)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtEstadoFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 288, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(278, 278, 278)
                .addComponent(btnLimpaCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLimpaCampos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigoFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCodigoFornecedor)
                    .addComponent(jLabel1)
                    .addComponent(txtEstadoFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNomeFantasia)
                    .addComponent(jLabel2)
                    .addComponent(txtCidadeFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRazaoSocial)
                    .addComponent(txtRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtBairroFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmailFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmailFornecedor)
                    .addComponent(jLabel4)
                    .addComponent(txtLogradouroFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefoneFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelefoneFornecedor)
                    .addComponent(jLabel5)
                    .addComponent(txtComplementoFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCNPJ)
                    .addComponent(jLabel6)
                    .addComponent(txtNumeroFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(txtCepFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/save_disk_22124.png"))); // NOI18N
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/EXCLUIR.fw.png"))); // NOI18N
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ATUALIZAR.fw.png"))); // NOI18N
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/create-list-button_icon-icons.com_54025.png"))); // NOI18N
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        tblFornecedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFornecedorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblFornecedor);

        btnLimpa.setText("Limpa tabela");
        btnLimpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnLimpa)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnListar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLimpa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigoFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoFornecedorActionPerformed

    private void txtEmailFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailFornecedorActionPerformed

    private void txtTelefoneFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefoneFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefoneFornecedorActionPerformed

    private void txtCNPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCNPJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCNPJActionPerformed

    private void txtContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContatoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
      
        if(FornecedorCL.newFornecedor(read())){
            JOptionPane.showMessageDialog(null, "Fornecedor cadastrado com sucesso");
           limpaTelaFornecedor();
            
             
        }else{
             JOptionPane.showMessageDialog(null, "erro ao cadastrar");
        }
        
        retrieveFornecedor();
        
        
        

        
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        retrieveFornecedor();
       
    }//GEN-LAST:event_formInternalFrameOpened

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        // TODO add your handling code here:
        
        retrieveFornecedor();
    }//GEN-LAST:event_btnListarActionPerformed

    private void tblFornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFornecedorMouseClicked
        // TODO add your handling code here:
        
        if(tblFornecedor.getSelectedRow()>-1){
            int linha = tblFornecedor.getSelectedRow();
            DefaultTableModel conteudo = (DefaultTableModel) tblFornecedor.getModel();
            FornecedorBO c = FornecedorCL.findFornecedorCodigo(Integer.valueOf(conteudo.getValueAt(linha, 0).toString()));
            writeFornecedor(c);
          
        }
    }//GEN-LAST:event_tblFornecedorMouseClicked

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        int codigo = Integer.parseInt(txtCodigoFornecedor.getText());
        int linha = tblFornecedor.getSelectedRow();
        FornecedorCL.deleteFornecedor(codigo);
        ((DefaultTableModel) tblFornecedor.getModel()).removeRow(linha);
        limpaTelaFornecedor();
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
         
        if(FornecedorCL.updateFornecedor(read())){
            JOptionPane.showMessageDialog(null, "Fornecedor atualizado com sucesso");
             limpaTelaFornecedor();
        }else{
        JOptionPane.showMessageDialog(null, "erro ao atualizar!");
        }
        
       
        
        
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnLimpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpaActionPerformed
   CriatabelaVazia();
        
    }//GEN-LAST:event_btnLimpaActionPerformed

    private void btnLimpaCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpaCamposActionPerformed
      limpaTelaFornecedor();
    }//GEN-LAST:event_btnLimpaCamposActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimpa;
    private javax.swing.JButton btnLimpaCampos;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCNPJ;
    private javax.swing.JLabel lblCodigoFornecedor;
    private javax.swing.JLabel lblEmailFornecedor;
    private javax.swing.JLabel lblNomeFantasia;
    private javax.swing.JLabel lblRazaoSocial;
    private javax.swing.JLabel lblTelefoneFornecedor;
    private javax.swing.JTable tblFornecedor;
    private javax.swing.JTextField txtBairroFornecedor;
    private javax.swing.JTextField txtCNPJ;
    private javax.swing.JTextField txtCepFornecedor;
    private javax.swing.JTextField txtCidadeFornecedor;
    private javax.swing.JTextField txtCodigoFornecedor;
    private javax.swing.JTextField txtComplementoFornecedor;
    private javax.swing.JTextField txtContato;
    private javax.swing.JTextField txtEmailFornecedor;
    private javax.swing.JTextField txtEstadoFornecedor;
    private javax.swing.JTextField txtLogradouroFornecedor;
    private javax.swing.JTextField txtNomeFantasia;
    private javax.swing.JTextField txtNumeroFornecedor;
    private javax.swing.JTextField txtRazaoSocial;
    private javax.swing.JTextField txtTelefoneFornecedor;
    // End of variables declaration//GEN-END:variables
}
